AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-s3-movefiles
  AWS Lambda function triggered by an S3 event.

Resources:
  # 📌 Función Lambda que procesa archivos de S3
  XLSProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./HelloWorldFunction/target/lambda.zip
      Handler: helloworld.XLSHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Timeout: 20
      Environment:
        Variables:
          INPUT_BUCKET: inputbucketlcy  # Referencia directa al bucket existente
          OUTPUT_BUCKET: outputbucketlcy  # Referencia directa al bucket existente
      Policies:
        - S3ReadPolicy:
            BucketName: inputbucketlcy  # Referencia directa al bucket existente
        - S3WritePolicy:
            BucketName: outputbucketlcy  # Referencia directa al bucket existente

  # 📌 Permiso para que el bucket de entrada invoque la función Lambda
  S3EventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt XLSProcessingFunction.Arn
      Principal: "s3.amazonaws.com"
      SourceArn: !Sub "arn:aws:s3:::inputbucketlcy"

Outputs:
  XLSProcessingFunction:
    Description: "ARN de la función Lambda"
    Value: !GetAtt XLSProcessingFunction.Arn