name: Build release branches

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    build-main:
      name: Build for main
      if: ${{ github.ref_name == 'main' && !contains(github.event.head_commit.message, 'github_sha') }}
      uses: turnitin/github-actions/.github/workflows/triton-build-without-sar.yaml@DEVOPS-18867
      with:
        environment: dev
        app_name: serverless-v1-demo-java
        release_repository: turnitin/serverless-v1-demo-java
        configure_java: true
        use_container: ""
        use_samconfig: true
      secrets: inherit
