name: Set repository secret
run-name: Set repository secret ${{ inputs.secret_name }}

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: Name of the secret
        type: string
      secret_value:
        description: Value to set for the secret
        type: string

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mask secret value
        run: |
          SECRET_VALUE=$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)
          echo ::add-mask::$SECRET_VALUE
          echo SECRET_VALUE=$SECRET_VALUE >> $GITHUB_ENV
      - name: Set secret
        run: |
          gh secret set "$SECRET_NAME" --body "$SECRET_VALUE" --repo "$REPO_NAME"
        env:
          GH_TOKEN: ${{ secrets.TRITON_PERSONAL_ACCESS_TOKEN }}
          SECRET_NAME: ${{ inputs.secret_name }}
          REPO_NAME: ${{ github.repository }}